version: '3'
services:
  nginx:
    #if nginx crash; restart it always
    restart: always
    depends_on:
      - my-rest-api
    build:
      context: ../my-nginx
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
  my-rest-api:
    depends_on:
      - my-redis
    build:
      context: ../my-rest-api
      dockerfile: Dockerfile
    volumes:
      - /home/erol/tmp/logs:/logs
    environment:
      - API_VERSION=v5
      - REDIS_HOST=my-redis
      - REDIS_PORT=6379
  my-redis:
    image: redis